### PR TITLE
Migrate to Compose V2

### PR DESCRIPTION
**Pull request by mrsarm**
The `docker-compose` command and the versioning and name convention for the `docker-compose.yml` file are deprecated in favor of the `docker compose` command built in `docker`, and `compose.yml` is now the preferred way to name the file. Reference: [Migrate to Compose V2](https://docs.docker.com/compose/migrate/).

As mention in the cited link:
> For most projects, switching to Compose V2 requires no changes to the Compose YAML or your development workflow.

So the change is backward compatible, and still works with the `docker-compose` command, which is no longer updated, and at some point is going to be incompatible with newer versions of Docker, although not soon.

Also the `version` keyword although supported is useless: https://github.com/compose-spec/compose-spec/blob/master/04-version-and-name.md#version-top-level-element

### CODE REVIEW

**Comment by mrsarm** [comment]
Hi @mrjones-plip and @joshnesbit !

Hope this is useful, but don't feel obligated to merge it if you think the changes are going to cause troubles, although it shouldn't but the opposite in the future.

**Review by jkuester — COMMENTED** [review]
The doc changes are great @mrsarm!  I am curious about the `docker-compose.yml` > `compose.yml` change?  Maybe I am missing something here, but [the compose docs](https://docs.docker.com/compose/compose-file/compose-file-v3/#service-configuration-reference) still say:

> The default path for a Compose file is `./docker-compose.yml`

Is there a reason we should not use the default naming here?

**Comment by mrsarm** [comment]
Yes actually that document you pointed out is old and deprecated, and I don't blame you because it's actually hard to understand the current state of the Compose project, they did a terrible work communicating the changes.

Compose V1 and Compose V2 are not the same than the "version" field in the compose file, it's `docker-compose` (deprecated) vs `docker compose`, the page you mention still have V1 specs, but you can see that it points to a Github page that contains the latest changes in regards to the file spec:

> The Compose file is a YAML file defining services, networks, and volumes for a Docker application. The latest and recommended version of the Compose file format is defined by the [Compose Specification](https://github.com/compose-spec/compose-spec/blob/master/spec.md).

In that specification, section [Compose file](https://github.com/compose-spec/compose-spec/blob/master/spec.md#compose-file) says:

> The default path for a Compose file is `compose.yaml` (preferred) or `compose.yml` in working directory. Compose implementations SHOULD also support docker-compose.yaml and docker-compose.yml for backward compatibility. If both files exist, Compose implementations MUST prefer canonical compose.yaml one.

I did not used the `yml` extension but the `yaml` one, that still is in the list of recommended, because is more widely used that the last one.

**Comment by mrjones-plip** [comment]
TIL!  That's interesting.  Here's a quick test I did (see below).  We might consider updating `docker-compose.yml` -> `compose.yaml` when we do [the v1 -> v2 work](https://github.com/medic/cht-docs/issues/1063)! 

https://github.com/medic/nginx-local-ip/assets/8253488/43ee0ab8-9241-4f51-839f-591ab96a0038

**Comment by mrsarm** [comment]
> We might consider updating docker-compose.yml -> compose.yaml when we do https://github.com/medic/cht-docs/issues/1063!

I changed the extension from `.yml` to `.yaml`, more standard. But yes, feel free to merge when it's the right moment, or just discard the changes if you are going to change it as part of a larger refactor.

**Comment by mrjones-plip** [comment]
oh no!  I didn't mean for you to make the change here (but thank you!!), I meant maybe when we update the `[cht-docs` repo](https://github.com/medic/cht-docs/) we should use the `compose.yaml` convention.

Your changes are welcome though!

**Review by jkuester — APPROVED** [review]
Thanks @mrsarm for the detailed explanation!  That is super helpful and is definitely going to be a consideration for me going forward for other projects.

**Pull request merged**
