### PR TITLE
feat(#24) Default to local-ip.medicmobile.org

### LINKED ISSUE #24: Update to use local-ip.medicmobile.org
With the [DNS issues](https://github.com/medic/cht-core/issues/8100) that have been happening with local-ip.co, we should update this project to allow the URLs of the full chain and private key to be passed in docker compose variables.  We can then have them default to use the new and more stable service local-ip.medicmobile.org, but still be backwards compatible with local-ip.co and forwards compatible with any other provider in this space.

### PR DESCRIPTION
**Pull request by mrjones-plip**
This PR:
* Adds 4 new environment variables for the docker compose file
* Defaults 4 new variables to use `local-ip.medicmobile.org` and not use `local-ip.co`
* Updates Readme with instructions on how to use other providers, including `local-ip.co` 
* Is backwards compatible  `local-ip.co` and forwards compatible with any other provider

closes #24

### CODE REVIEW

**Comment by mrjones-plip** [comment]
@mrsarm  - sorry to do the work when you offered!  I needed to test [something](https://github.com/medic/cht-core/issues/8213) and it was pretty easy to figure out after you and I chatted.  

If you're still interested in helping, you can do the PR review here!

**Comment by mrsarm** [comment]
> @mrsarm - sorry to do the work when you offered! I needed to test [something](https://github.com/medic/cht-core/issues/8213) and it was pretty easy to figure out after you and I chatted.
> 
> If you're still interested in helping, you can do the PR review here!

Hey @mrjones-plip , thanks and sorry I couldn't start it earlier as I thought I would. Looks good, didn't test it yet, what caught my attention is that you committed a few IntelliJ files, I would instead remove them from the repo and add in the `.gitignore` file at the root an entry like `/.idea` to omit the IDEA config of the developer is working on the project. What you think?

**Comment by mrjones-plip** [comment]
good catch - thanks @mrsarm !  Fixed in 7033dcf.

**Review by mrsarm — APPROVED** [review]
Worked for me :+1:

**Review by jkuester — APPROVED** [review]
LGTM!  I love that it is not configurable to use other cert providers too!

**Comment by jkuester** [comment]
:facepalm:  :rofl: 

Yes!

**Pull request merged**
